inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

Performance/StringIdentifierArgument:
  Enabled: false
