inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

RSpec/IndexedLet:
  Max: 3

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

Performance/StringIdentifierArgument:
  Enabled: false
